name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            extra_packages: ""
          - os: ubuntu-26.04
            extra_packages: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get GCC version
        run: gcc --version

      - name: Get CMake version
        run: cmake --version

      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Update packages
        run: sudo apt-get update

      - name: Install packages PMP depends on
        run: >
          sudo apt-get install -y
          libtag1-dev
          default-libmysqlclient-dev
          qt6-base-dev
          qt6-multimedia-dev
          ${{ matrix.extra_packages }}

      - name: Configure PMP
        run: cmake -B bin -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: Build PMP
        run: cmake --build bin --parallel -- -k 100

      - name: Run tests
        run: ctest --test-dir bin -V --no-tests=error
